services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlsrv
      - key: DB_HOST
        value: 16.171.148.89
      - key: DB_PORT
        value: 1433
      - key: DB_DATABASE
        value: Exides
      - key: DB_USERNAME
        value: samu
      - key: DB_PASSWORD
        value: ContraSql